### ISSUE TITLE
При старте программы непонятно, что в данный момент происходит авторизация

### ISSUE THREAD

**Issue by dimkanovikov** [dimkanovikov/KITScenarist#117]
Когда запускаю программу иногда нужно подождать 5-10 секунд перед тем, как программа авторизуется в личном кабинете, но совершенно непонятно, что это происходит. Предлагаю сделать какую-нибудь визуальную индикацию процесса авторизации после загрузки. Например написать вместо ссылки "Авторизация" текст "Подключаюсь к сереру..." (у которого три точки в конце добавляются/исчезают) и сделать эту ссылку недоступной, до того момента, как не закончится авторизация.

**Comment by Armijo38** [comment]
Никогда не наблюдал 5-10 секунд. Обычно 1-2. Как тебе это удалось?

**Comment by dimkanovikov** [comment]
А у меня сегодня утром конфликтовали ip на двух устройствах, видимо это послужило причиной...

**Comment by dimkanovikov** [comment]
Отлично вышло!
