### ISSUE TITLE
Улучшить UX добавления проектов в разработке, сцен и папок в сценарии

### ISSUE THREAD

**Issue by dimkanovikov** [dimkanovikov/KITScenarist#125]
Текст в окне должен меняться с "Название" на "Необходимо ввести название".

**Comment by Nashev** [comment]
А что будет, если название не заполнят? Зачем заставлять?

**Comment by dimkanovikov** [comment]
Документ просто не будет сохранён без названия. Не вижу смысла в том, чтобы иметь документы без названий. Они должны иметь названия, чтобы между ними можно было легко ориентироваться.

**Comment by Nashev** [comment]
В Evernote, например, незаполненное название заметки делается при сохранении автоматом из первых слов содержимого. Кому надо - может потом исправлять сколько угодно.

Сам по себе подход с принуждением часто воспринимается как нечто неприятное, и по возможности его стоит избегать

**Comment by dimkanovikov** [comment]
Если речь идёт о текстовых заметках, то согласен, такой подход работает, но как быть при добавлении галереей изображений или ментальной карты?

**Comment by Nashev** [comment]
Воткнуть дату, например. Или дату с припиской о типе содержимого.
«картинка от 06.04.2017 16:26»

**Comment by dimkanovikov** [comment]
А давайте сделаем так. С другой стороны это уберёт один шаг, на пути добавления элементов. В таком варианте вообще можно от диалога отказаться...

**Comment by dimkanovikov** [comment]
Will be implemented in the Starc.
