### ISSUE TITLE
Проверить кеширование списка проектов для работы в офлайн режиме

### ISSUE THREAD

**Issue by dimkanovikov** [dimkanovikov/KITScenarist#19]
Если в прошлую сессию пользователь был залогинен, а сейчас включил прогу и нет инета, то должен подгружаться закешированный список проектов и он становится, как бы авторизован в фейк-режиме. Чтобы иметь возможность продолжать работать с ними в офлайн. А когда интернет появится они должны быть синхронизированы.

**Comment by dimkanovikov** [comment]
Я сейчас потестировал этот момент. Не происходит фейковой авторизации. Если в предыдущую сессию я был авторизован. Выключаю интернет. Перезапускаю программу. Мне отображена ссылка на авторизацию, списка проектов из облака нет.

Перевожу в ошибку.

**Comment by Armijo38** [comment]
1. Только при отсутствующем интернете авторизовывать в фейк-режиме? Что если пользователь на одном ПК меняет пароль и запускает программу на втором. Авторизация на втором не проходит, поскольку пароль неверен.
2. Сейчас такая возможность есть в ветке master (ApplicationManager.cpp конец метода aboutSyncClosedWithError). Почему этот код удален в ветке new-cabin?

**Comment by dimkanovikov** [comment]
1. Всё правильно. Фейк-режим используется только в случае с отсутствующим интернетом при старте приложения. Но если пользователь сменил пароль на другом компе, а на втором запускает в офлайне, то фейк-авторизация конечно проходит, т.к. подключения к интернету нет и она не знает о том, что пароль сменился.
2. Это не то, там какой-то сумбурный код, который использовался при переходе в автономный режим.

В итоге надо вот что: я включаю программу - интернета нет - если есть сохранённый логин, пароль и список проектов, то показываем будто пользователь авторизовался под этим именем и отображаем сохранённый список проектов (по-видимому надо ещё сохранять его имя пользователя и срок действия подписки, чтобы подгружать их тоже).

Если появляется интернет, то программа должна переавторизовать пользователя и синхронизировать текущий проект, если открыт.
