### ISSUE TITLE
Вынести проверку орфографии в отдельный поток

### ISSUE THREAD

**Issue by dimkanovikov** [dimkanovikov/KITScenarist#200]
Смотри SpellCheckTextEdit. Сейчас проверка выполняется в самом гуишном потоке, временами делая QApplication::processEvents. Надо, чтобы проверка орфографии выполнялась в отдельном потоке и при нахождении ошибок выстреливала соответствующий сигнал, а редактор в свою очередь будет устанавливать стиль для слов с ошибками.

**Comment by dimkanovikov** [comment]
Alexey, [01.06.17 22:41]
У меня есть мега идея как легко дать ему прирост скорости
Завести небольшой кэш и пусть там хранятся последние 50 слов с вердиктами для них. Когда пользователь редактирует абзац, то спеллчекеру всегда идёт один и тот же набор слов, а тут мы не спеллчекеру подаём, а в кэше находим.

**Comment by dimkanovikov** [comment]
+ не лишним будет обновить библиотеку hunspell

**Comment by henrikp** [comment]
I'm sorry if I'm hijacking this dead thread but curious, why isn't KIT Scenarist using system libaries for hunspell? Last release was in 2018 (1.7) and the included libraries are 1.3.2. Making a package for Gentoo and would like to use system packages as much as possible, can I do a PR if there aren't any blockers?

**Comment by dimkanovikov** [comment]
Hello, my friend. It's a good idea, but the reason, why we do that way, is that the application cross-platform, so we need to use common solution for all platforms and we do it one time :)

I agree, that for future updates it will be good to research a more accurate method.
