### ISSUE TITLE
В диалог выбора языка добавить возможность пользователю написать о том, что он хочет добавить поддержку нового языка

### ISSUE THREAD

**Issue by dimkanovikov** [dimkanovikov/KITScenarist#21]
Например кнопка, которая открывает диалог отправки фидбека, или ссылка на wiki-страницу о том, как можно добавить новый язык в программу

**Comment by Armijo38** [comment]
Обязательно ли только поддержку языка? Можно добавить простую форму для любого обратного фидбека.

**Comment by dimkanovikov** [comment]
Добавил мануал в вики https://github.com/dimkanovikov/KITScenarist/wiki/How-to-add-the-translation-of-KIT-Scenarist-to-your-native-language-or-improve-one-of-existing%3F
