### ISSUE TITLE
Программа должна загружать информацию о стоимости продления подписки с сервера

### ISSUE THREAD

**Issue by dimkanovikov** [dimkanovikov/KITScenarist#29]
В момент авторизации, сервер должен отдавать информацию о стоимости подписки для пользователя на разные периоды.

**Comment by dimkanovikov** [comment]
Я добавил в метод _api/account/login/_ поле _payment_month_ (оно идёт после всех ранее присутствовавших данных). Надо информацию из него сохранять и использовать для расчёта выводимой стоимости. Пункты со скидкой такими и остаются.

**Comment by Armijo38** [comment]
Скорее в 66% скидка, поскольку сейчас месячный платеж у меня 99, а был 299 :).
Думаю, если не обнаружили эту информацию, мне стоит кинуть ошибку авторизации

**Comment by dimkanovikov** [comment]
:) Да, хорошая мысль.
