### ISSUE TITLE
Search function on Synopsis not working

### ISSUE THREAD

**Issue by Shylon** [dimkanovikov/KITScenarist#354]
I am using latest RC from AUR repository, and in Research -> Synopsis , Ctrl + F then search for a word can't find anything.

**Comment by cyrant** [comment]
Подтверждаю. Нигде, кроме "Сценария", искомое слово не подсвечивается,
кнопки на всплывающей панели не работают. В версии 0.7.0 панель поиска в
этих местах не появлялась совсем.

**Comment by dimkanovikov** [comment]
You are guys hackers! Search panel was not implemented for this type of research items but was available through the shortcut key!:) Will implemented in future versions.

**Comment by Shylon** [comment]
Sorry for late, Yes, I can reproduce the issue, both on windows and linux manjaro RC3, same problem even if making a new project there is an additional card and seems a copy.

**Comment by Shylon** [comment]
Thank you, As a suggestion, it would be nice to see more Categories on Research (Like Character is there), more Items like OBJECTS, ANIMALS etc...

**Comment by dimkanovikov** [comment]
Hmm. But you can create in manually. Like this

![research-additional-categories](https://user-images.githubusercontent.com/685583/26872245-8a5ddb16-4b7e-11e7-96a1-7680fac51e52.png)

**Comment by yury-SB** [comment]
Fixed in 0.7.2 rc10
