### ISSUE TITLE
Cards not working properly.

### ISSUE THREAD

**Issue by Shylon** [dimkanovikov/KITScenarist#355]
I am using latest RC from Arch AUR on Manjaro, first I can't delete default card, and when I add new card the empty one (first one) is somehow mixed with other cards, and also they arrange randomly.
this is very annoying problem.

**Comment by dimkanovikov** [comment]
@Shylon it's like a bug of projects was been created in older versions. Can you reproduce this bug with projects created in latest app version (0.7.1rc3)?

**Comment by cyrant** [comment]
Версия 0.7.1rc3.
1) Создаю новый проект. Добавляю карты сцены со случайным содержимым, затем удаляю их в произвольном порядке. Последняя карта на доске при удалении не исчезает и сохраняет своё содержимое. Но новая добавляется взамен неё, словно та всё-таки была удалена.
2) Создаю новый проект. Добавляю карту акта и сразу удаляю её. Взамен неё появляется карта сцены, которую нельзя удалить, изменить или переместить. С этого момента при операциях с картами начинаются какие-то аномалии.

**Comment by dimkanovikov** [comment]
@cyrant спасибо. Буду исследовать.

Одна карточка будет оставаться в любом случае - это нормальное поведение. Вопрос в том, чтобы её содержание очищалось тоже и после этого всё работало корректно.

**Comment by Shylon** [comment]
Sorry for late, Yes, I can reproduce the issue, both on windows and linux manjaro RC3, same problem even if making a new project there is an additional card and seems a copy.
