### ISSUE TITLE
В убунте иногда обновление открывается в менеджере архивов

### ISSUE THREAD

**Issue by dimkanovikov** [dimkanovikov/KITScenarist#371]
Думаю стоит запретить вообще автоматическую установку в линуксе...

**Comment by Armijo38** [comment]
Предлагаю явно запустить software-center с путем до файла

**Comment by dimkanovikov** [comment]
Можно попробовать, если это возможно. Тут ещё есть момент, что в Elementary нет центра приложений, так что её нужно будет убрать из этого списка.
