### ISSUE TITLE
Проблемы с новым скроллбаром

### ISSUE THREAD

**Issue by Armijo38** [dimkanovikov/KITScenarist#372]
Новый скролл можно переместить в самый низ, закрыв при этом нижнюю кнопку-треугольник (аналогично и вверх). При этом, на саму кнопку все еще можно нажать.

**Comment by dimkanovikov** [comment]
Проблема в том, что когда ползунок находится над кнопкой, то нажимается кнопка, а не происходит захват ползунка.

**Comment by dimkanovikov** [comment]
Already implemented in the Starc.
