### ISSUE TITLE
Allow Bold and Italics (with keyboard shortcuts)

### ISSUE THREAD

**Issue by laserstrike** [dimkanovikov/KITScenarist#406]
Hi. I can't seem to get ctrl + B or ctrl + I to use bold or italics when writing. I looked at the template settings and there IS an option there to have certain sub-formats like Character, Dialogue, Action always be in capitals, bold, or italics. But I'd like to be able to use it only for certain words, at certain times.

Maybe I missed a menu somewhere. 

If not, please consider this for a future release. Thank you.

**Comment by dimkanovikov** [comment]
Hello, laserstrike. Thanks for your suggestion. We plan to add this feature in one of the next releases.
