### ISSUE TITLE
Проблемы с восстановлением соединения

### ISSUE THREAD

**Issue by Armijo38** [dimkanovikov/KITScenarist#407]
Писал сценарий в облаке. Увел мак в спящий режим. Пробудил. Облако зеленым не становилось.

**Comment by dimkanovikov** [comment]
Тут ещё сообщали о том, что в маке приложение часто запускает подряд две волны - зелёную, а в след за ней красную, через минуту опять и так без остановки...

**Comment by dimkanovikov** [comment]
Не удалось воспроизвести ни один из кейсов...
