### ISSUE TITLE
Ошибка сборки на Raspberry Pi

### ISSUE THREAD

**Issue by guerrrero** [dimkanovikov/KITScenarist#504]
Использую Qt 5.7.1, который, как оказалось, _уже_ не поддерживает qtwebengine и qtwebenginewidgets, которые используются при мейке. Более старых версий QT в репах не нашел, а собирать целый Хромиум и либы на Pi это долгий ужас-кошмар (а это придется, даже если сменить qtwebengine на qtwebkit), поэтому обращаюсь за помощью:
1) Что бы сделать, чтобы заработало?
2) Если мимо пройдет какой-нибудь добрый самаритянин с перком кросс-компилинга для RPi (архитектура armhf) - ох, это было бы просто божественно.

**Comment by dimkanovikov** [comment]
Здравствуйте. Это очень странно, видимо версия Qt, которая собирается под RPi не имеет своих модулей qtwebengine и qtwebenginewidgets. Так-то в ванильной версии как раз перешли с webkit на webengine и он теперь присутствует во всех версиях начиная с 5.6 и до 5.10 (мы сами для сборки на разных системах используем разные версии Qt и, кстати говоря, Linux-версия собирается с Qt 5.7.1)...

Что я могу порекомендовать:
1. Собирать вручную, или поискать репозитории, в которых данные модули поддерживаются.
2. Можете попробовать сделать небольшой патч, в котором выпилить эти модули из программы, в принципе они касаются только раздела разработки и используются для отображения ссылок добавленных пользователем.
3. О других сборках под Raspberry не слышал пока.

**Comment by dimkanovikov** [comment]
Сейчас сборка для Raspbian есть на [opensuse](https://software.opensuse.org/download.html?project=home%3AAndnoVember%3AKITScenarist&package=kitscenarist)
