### ISSUE TITLE
Setup Travis-CI for autobuild AppImage (portable package for Linux) 

### ISSUE THREAD

**Issue by Symbian9** [dimkanovikov/KITScenarist#527]
Providing an <a href="https://appimage.org">AppImage</a> would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, <a href="http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80">make it executable</a>, and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with appimaged
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the <a href="https://appimage.github.io/apps">AppImageHub</a> central directory of available AppImages

<a href="https://github.com/AppImage/AppImageKit/wiki/AppImages">Here is an overview</a> of some projects that are already distributing upstream-provided, official AppImages.

https://github.com/probonopd/linuxdeployqt has lots of real-world examples on how to do this. Let @probonopd know if something is not clear or you need some help.

https://github.com/probonopd/uploadtool script will help you setup Travis-CI for uploading built AppImage's automatically back to Github repo in "Releases" section.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net

Ask @probonopd for help you on Github ;-)

**Comment by probonopd** [comment]
I have started working on it. As part of the build, I use

```
qmake CONFIG+=release PREFIX=/usr
make -j$(nproc)
make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
```
but I am running into this issue:

```
make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
```

I would expect it to be installed into the `appdir/usr/...` filesystem hierarchy.

Please advise.

References:
* https://github.com/probonopd/KITScenarist/blob/patch-1/.travis.yml
* https://www.travis-ci.org/probonopd/KITScenarist/builds/320209195#L1348

**Comment by dimkanovikov** [comment]
Thanks guys for your suggestions, but we don't need that.

**Comment by probonopd** [comment]
Why not? It makes it much easier to download and use your software.

**Comment by dimkanovikov** [comment]
Because we already have installers for most distributions.

**Comment by probonopd** [comment]
Installer != easy. But your choice.

**Comment by dimkanovikov** [comment]
Come on, guys, installer == habitually. I think that if a user can do some stuff the usual way, it's not good practice to make him do extra moves...
