### ISSUE TITLE
Empty Name in Cast Reports

### ISSUE THREAD

**Issue by X-Raym** [dimkanovikov/KITScenarist#555]
Hi,

The Cast Reports sometimes shows an empty name entry which doesn't match any characters.

Here is an example from the  Brick & Steel by Stu Maschwitz script downloaded from the samples available at [afterwriting.com](https://afterwriting.com/#):

![Screenshot](https://monosnap.com/file/ZXWbBljs6tZSN0OyekST6uVcHkRpVa.png)

And here is the character list:
![Screenshot](https://monosnap.com/file/vo2koVbbFBWryPi9Co6s8ZFObRkfKF.png)

I got the same thing with other files, but I didn't find what this happen in the reports.

What's wrong ?

Thanks !

**Comment by dimkanovikov** [comment]
Hello. Thanks! It's a bug of automatic text corrections on page breaks. Will be fixed in future update.

P.S. I received your mail and will send a reply today.

**Comment by X-Raym** [comment]
@dimkanovikov Thanks :)

> P.S. I received your mail and will send a reply today.

Please take your time. Cheers!
