### ISSUE TITLE
Добавить статью в справку о том, как можно установить приложение в Арче без сборки

### ISSUE THREAD

**Issue by dimkanovikov** [dimkanovikov/KITScenarist#571]

**Comment by cyrant** [comment]
Не совсем понимаю, о чем идёт речь?

**Comment by dimkanovikov** [comment]
Да тут предложили на форуме такой способ, http://www.hoer-talk.de/threads/skriptsoftware-kit-scenarist.27773/page-7#post-353643, подумал, что можно вынести на вики сюда.

**Comment by cyrant** [comment]
Ага. Там предлагают PKGBUILD для установки уже скомпилированной программы из самодостаточного deb-пакета с вашего сайта. Если хотите, я могу "оформить" его на AUR, как альтернативу. Тогда пользователи смогут установить и обновлять программу штатными средствами, а не вручную каждый раз.

**Comment by dimkanovikov** [comment]
@cyrant найс!:) Спасибо большое!

**Comment by cyrant** [comment]
Похоже, у вас в пакете не совсем корректные права доступа у файлов - 7**7**5. Если верить документации ([1](https://wiki.debian.org/Debate/umask), [2](https://wiki.debian.org/Permissions#The_defaults_for_new_files_and_directories)), то у стокового Debian'а должны быть 7**5**5, (как и в Arch'е: [umask 0**2**2](https://git.archlinux.org/svntogit/packages.git/tree/trunk/profile?h=packages/filesystem)):
> The umask of a 'stock' Debian system is 0022 which makes the default permissions be 0755 -- the owner has all permissions, the **group read and execute but not write**, and everybody else can read and execute but not write.

**Comment by dimkanovikov** [comment]
Была такая задачка #548, видимо невнимательно посмотрел. Спасибо, перепроверим.
