### ISSUE TITLE
Как собирать проект?

### ISSUE THREAD

**Issue by kuraleb** [dimkanovikov/KITScenarist#578]
Добрый день.

Мне нужно собрать 5-ю бету под 32 битный процессор Atom.

Выгружаю из гита проект + ядро в директорию ./src/bin/scenarist-core

Сперва натолкнулся на ошибку: 
"scenarist-desktop/UserInterfaceLayer/Statistics/StatisticsView.cpp:142:25: error: ‘isnan’ was not declared in this scope"

Решил включение в файл StatisticsView.cpp:
#include <math.h> / isnan, sqrt /

Далее ошибка по ядрёнее и уже в ядре:

"scenarist-core/3rd_party/Widgets/PagesTextEdit/PageTextEdit.cpp:2139:22: error: ‘class QWidgetTextControl’ has no member named ‘isPreediting’
&& !control->isPreediting()) {"

Проблема обходится удалением "&& !control->isPreediting()" в PageTextEdit.cpp

Приложение собралось, но нуждается в куче либ. Они в проекте вроде как есть.

Там есть скрипт для генерации deb пакетов. Но в директории откуда он берет файлы - есть не всё. И основной вопрос отсюда. Это скрипт сборки их туда не подкладывает или я сам должен туда каждый файл подкладывать?))

**Comment by kuraleb** [comment]
Худо бедно собрал. Файлы вручную подложил.
Воспользовался скриптом сборки deb пакетов.

При запуске возникает следующая ошибка.

This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Aborted

**Comment by kuraleb** [comment]
Ура. Программа запущена.

Но возник вопрос. Зачем qt плагины присутствют в самом приложении, если можно воспользоваться лишь зависимостями?

**Comment by dimkanovikov** [comment]
Плагины подгружаются только во время выполнения. Невозможно заранее предугадать какую систему использует пользователь xcb или xlib, поэтому все плагины подкладываются рядом и во время работы приложения, оно определяет какой именно нужно использовать и загружает его для дальнейшего использования. По остальным моментам на днях подготовлю wiki и тут размещу.

**Comment by ghost** [comment]
Кстати, есть такая бяка:

> error: ‘isnan’ was not declared in this scope"

Лечится заменой isnan на std::isnan в 'scenarist-desktop/UserInterfaceLayer/Statistics/StatisticsView.cpp'. Без включения cишного <math.h> можно обойтись.
С [0.7.1rc2](https://aur.archlinux.org/cgit/aur.git/diff/PKGBUILD?h=scenarist&id=3c258943c6d9ccb7085e9812abeef4540e43383b) ещё тянется. Извиняюсь, что сразу не сказал.

**Comment by dimkanovikov** [comment]
@cyrant всё хорошо. Спасибо, так и сделаем.

**Comment by cyrant** [comment]
По теме вопроса, инструкция:

1. Установить зависимости способом, принятым в вашем дистрибутиве ОС.

> Под Arch Linux достаточно только пакета qt5-webengine (проверял в [чистом chroot-е](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_Clean_Chroot)), так как все остальные зависимости он тянет с собой. Предположу, что в других дистрибутивах также.

2. Притянуть исходный код программы.
```
$ git clone --depth 1 --branch 0.7.2.beta5 https://github.com/dimkanovikov/KITScenarist.git
$ cd KITScenarist
$ git submodule update --init
```
3. Собрать с помощью qmake, make и gcc.
```
$ qmake Scenarist.pro -spec linux-g++ && make
```
