### ISSUE TITLE
Export to .odt

### ISSUE THREAD

**Issue by WPFilmmaker** [dimkanovikov/KITScenarist#580]
Hi, I just noticed that KITScenarist only supports DOCX, PDF, FDX and Fountain.

I would like to request the ability to export to ODT as it an open format which I think it reflects the spirit of this software.

More importantly  it is the default format for Libreoffice (and other derivate such as OpenOffice) which means that most of the Linux distributions already ship the software to open and edit it (unlike PDF) and that does not require to install anything else (like Fountain). 

Also KITScenarist can already import .odt files so why not exporting as well?

Thank you very much

**Comment by dimkanovikov** [comment]
Hello.

The main reason is that the producers and production companies request not ODT-files, but DOCX (Russia and CIS, Asia, South America) or FDX (US, Canada, Europe, Australia, India). PDF is commonly used format for the industry, too. And Fountain didn't require anything else, it's just a markdown (read more here https://fountain.io) and it's open format created especially for screenwriting.

ODT is great, but its use is impractical if we talk about screenplays and film industry. So, we don't plan to support export to ODT.

P.S. As I know DOCX is open format too (https://en.wikipedia.org/wiki/Office_Open_XML).
