### ISSUE TITLE
ask r/Screenwriting/ to add KITScenarist to their screenwriters list

### ISSUE THREAD

**Issue by WPFilmmaker** [dimkanovikov/KITScenarist#584]
/Screenwriting is a popular subreddit about screenwriting, I noticed that KiTScenarist is not present in their "recommended section" (https://www.reddit.com/r/Screenwriting/wiki/resources#wiki_screenwriting_software). I would recommend the devs to ask to have it included as it would give a lot of visibility and his software certainly deserves it.

**Comment by dimkanovikov** [comment]
Hi! It's a great idea! I sent our suggestion to this article author. Hope he will add KIT Scenarist to list.

**Comment by yury-SB** [comment]
Mysterious Someone done it.
https://www.reddit.com/r/Screenwriting/wiki/meta/resources#wiki_3._formatting_resources
