### ISSUE TITLE
Bug: In some circumstances, the cursor disappear [Windows]

### ISSUE THREAD

**Issue by X-Raym** [dimkanovikov/KITScenarist#597]
Hi,

Usually, there is a small blinking vertical bar (the insertion cursor) to indicate the character in focus for insertion.

In some circumstances (it appears more or less randomly) this cursor disappear, and clicking doesn't restore it back.

Here is a demo:

![demo](https://i.imgur.com/0QIyJqs.gif)

See how it is missing even when I delete characters, then it reappears, and disappear again at character deletion.

It would to have it always visible cause it is a bit disturbing to not see where the focus is.

Thanks for listening !

(Windows 10 x64, Kit 0.7.2 beta 5)

**Comment by dimkanovikov** [comment]
Thanks for the report!

**Comment by dimkanovikov** [comment]
@X-Raym hey! Does problem happen only in the Windows operating system? Or in others too?

**Comment by X-Raym** [comment]
@dimkanovikov hi ! The problem was on Windows 10 x64, Kit 0.7.2 beta, I didnt test this paeticular issue on Mac or newer version.

**Comment by dimkanovikov** [comment]
@X-Raym thanks. I can't reproduce it on Linux and Mac OS, so, look like Windows related bug
