### ISSUE TITLE
Реализовать синхронизацию карточек

### ISSUE THREAD

**Issue by dimkanovikov** [dimkanovikov/KITScenarist#60]
1. реализовать методы API для синхронизации карточек на сервере
2. реализовать взаимодействие с API в программе

**Comment by Armijo38** [comment]
Предлагаю использовать тот же метод сохранения/загрузки текста сценария (https://kitscenarist.ru/api/projects/scenario/change/) . Необходимо лишь расширить xml.

**Comment by dimkanovikov** [comment]
Я думаю, что карточки будут храниться в виде цельного xml, а не патчами. Плюс возможна ситуация, когда карточки поменялись, а текст сценария не поменялся. Поэтому думаю, что следует разделить синхронизацию текста и карточек.

**Comment by Armijo38** [comment]
А как будет происходить совместное редактирование карточек.

**Comment by dimkanovikov** [comment]
Пока план такой, что совместное редактирование будет доступно только для текста сценария. Остальные части синхронизируются целиком. В процессе работы сервиса, если поймём, что нужна совместная работа для других модулей - разовьём это направление.
