### ISSUE TITLE
Линковать все либы статически

### ISSUE THREAD

**Issue by dimkanovikov** [dimkanovikov/KITScenarist#603]

**Comment by cyrant** [comment]
Надеюсь, это коснётся только виндовой сборки?

**Comment by dimkanovikov** [comment]
@cyrant это коснётся всех сборок. Но относится только к нашим внутренним библиотекам.

**Comment by cyrant** [comment]
@dimkanovikov А, отлично.

**Comment by dimkanovikov** [comment]
для винды ещё надо доработать

**Comment by cyrant** [comment]
У меня fileformats не линкуется без libz. [Патчик](https://aur.archlinux.org/cgit/aur.git/plain/build.patch?h=scenarist&id=08df73a6fb4f4f0de0394829f53a5c2e5bfcc4ae)

И shell-скрипты с LD_LIBRARY_PATH в build/{Rpm,Ubuntu}/*/usr/bin теперь не нужны. Можно сразу бинарник туда отправлять.

**Comment by dimkanovikov** [comment]
@cyrant мерси! На счёт LD_LIBRARY_PATH - у него долгая история, с тех времён, когда в репах был Qt 5.6, а нам нужен был 5.7, я так его с собой в пакете и таскаю... Переделаем на зависимости в будущих версиях.
