### ISSUE TITLE
Добавить возможность создавать сдвоенные диалоги

### ISSUE THREAD

**Issue by dimkanovikov** [dimkanovikov/KITScenarist#606]

**Comment by dimkanovikov** [comment]
Already implemented in the Starc.

**Comment by NoodleSushi** [comment]
How do I use the double dialogues feature? I couldn't find documentation or online discussions that could help me find it myself. Thanks in advance!

**Comment by dimkanovikov** [comment]
Hello @NoodleSushi ! In the KIT Scenarist you can't make a double dialogue, but you can do it in our next-gen app named [Starc](https://starc.app).

**Comment by aaronliu0130** [comment]
PLEASE re-add this. Starc currently doesn't have as much features.

**Comment by dimkanovikov** [comment]
Hello @aaronliu0130, what concrete features do you miss in the Starc?

**Comment by aaronliu0130** [comment]
1. Design langauge
    Starc currently uses material design. A lot of people (including me) don't like this ui design scheme, and prefer the gtk feel of story architect. Also, the first time setup screen of Starc doesn't have material fonts, making that ui look ugly.
2. Characters and Locations
    Starc required you to PAY to edit characters/locations directly from the charcters/locations screen! I understand having to pay for relations but this is ridiculous.
3. a lot
    Cards, plot statistics, the entire documents section from research, and script backup.
4. We don't have a major release yet.
    I don't think a project should be abandoned before 1.0.0 unless there is something horribly wrong with it. Plus, adding double dialogue to kit won't change starc, there's no harm in adding it. Just "this feature is present in another app we have" isn't enough reason to remove an already (half?) implemented feature.

**Comment by dimkanovikov** [comment]
> Design langauge

Design is always discussable and subjective. Material Design give me a strong framework, with concrete guidelines of how every thing should look like and how it should act. I remember how every new thing in KIT becomes headache, because I simply don't know how it should look like and different app's modules has different UI/UX principles.

> the first time setup screen of Starc doesn't have material fonts, making that ui look ugly.

Can you please share a screenshot and details about operating system where this happened? This is strange, since every bit of Starc UI built from scratch.

> Starc required you to PAY to edit characters/locations directly from the charcters/locations screen! I understand having to pay for relations but this is ridiculous.

Starc allow you to edit characters and locations, not via the characters relations/locations map modules, but via direct access to the characters and locations items (absolutely similar to the KIT Scenarist). Please, double check it.

> Cards, plot statistics

Planned to be implemented in the next month or two.

> the entire documents section from research, 

Same, but to the end of year (folders and text documents already here).

> script backup

Starc allow you to undo last editing even after app restart. The ability to walk through document changing history (which fully replace backups feature) also on the roadmap.

> I don't think a project should be abandoned before 1.0.0 unless there is something horribly wrong with it. Plus, adding double dialogue to kit won't change starc, there's no harm in adding it. Just "this feature is present in another app we have" isn't enough reason to remove an already (half?) implemented feature.

Actually, "something horribly with it". That's why I started the crowdfunding campaign in the 2019 (which was failed). KIT was designed as a simple text editor and building all that stuff around it have made it horrible, very hard to support and about to impossible to adding new features. And that's why adding double dialogues feature fully breaks any attempts to undo & redo screenplay changes/cards rebuilding/cloud syncing/etc. and was stashed and froze in the separate branch.

**Comment by aaronliu0130** [comment]
Really good points, especially the first and last one.

I can't find a way to bring that startup dialog box up again.
