### ISSUE TITLE
Improvements to your shop

### ISSUE THREAD

**Issue by WPFilmmaker** [dimkanovikov/KITScenarist#615]
I really like Alexander the Cat :) right now I can't, but hope to get one t-shirt in the future. I have a few suggestions for your shop page which I think would improve the clarity of the page:

- Specify approximatively the price of t-shirt in Dollars/Euros/British Pounds next to the price in Rubles (very few people outside Russia are familiar with Rubles).

- Specify approximatively the price for shipping costs in Dollars/Euros/British Pounds next to the price in Rubles (same as above).

- Specify approximatively the shipping days/weeks for the countries you listed.

- Specify which methods of payments can be used to pay (for instance paypall button).

Tip 1: In the future you might want to consider selling coffee mugs as well, as they are a very popular item.

Tip 2: The t-shirt costs approx. 19 dollars plus shipping costs, you could add a link in the shop page that redirects to your donation page for who want to donate smaller amount of money :)

Tip 3: I would recommend to specify the price in Dollars/Euros/British Pounds for your hosting services :)

**Comment by dimkanovikov** [comment]
@WPFilmmaker Thank you so much! It's really great thoughts. Will be updated!:)

**Comment by dimkanovikov** [comment]
done
