### ISSUE TITLE
Dual dialogue?

### ISSUE THREAD

**Issue by smvg** [dimkanovikov/KITScenarist#626]
This has probably been suggested before (I can't read Russian so... 😅) but it would be very cool if we could add dual dialogues to our scripts. Other than that, the application is AWESOME. Was about to buy a license for Fade In but I think KITScenarist will do it :)

Keep up the good work!

**Comment by dimkanovikov** [comment]
Hi! Yep, we plan to add this feature in the nearest update. Duplicate of the #606
