### ISSUE TITLE
Слова типа How're некорректно добавляются в орфографический словарь

### ISSUE THREAD

**Issue by dimkanovikov** [dimkanovikov/KITScenarist#645]
вместо фразы целиком добавляется либо how либо re, в зависимости от того, где был курсор. А надо целиком, вместе с апострофом.

**Comment by imgforge** [comment]
Excellent.

**Comment by dimkanovikov** [comment]
Остался неохваченным один вариант использования, когда апостроф ставится в конце слова

Making plural nouns possessive

Add an apostrophe only to plural nouns that already end in s.

You don’t need to add an extra ‘s’ to plural nouns that already end with the letter ‘s’. Simply tuck the apostrophe onto the end to indicate that the plural noun is now a plural possessive noun.

Examples:
```
    Companies’ workers
    Horses’ stalls
    Countries’ armies
```
