### ISSUE TITLE
Crash, when using Consextmenu in "Research" / macOS

### ISSUE THREAD

**Issue by ovalmartini** [dimkanovikov/KITScenarist#69]
... Scenarist always crashes, when I try to open the context-menu in the Research-Field.

**Comment by dimkanovikov** [comment]
@ovalmartini thanks for feedback! Can you attach file with text of crash report which system showed? And add more details: in what part of research module I need to click to reproduce this?

**Comment by ovalmartini** [comment]
works now, I don't know, what it was. I will post the report when it happens again...

**Comment by dimkanovikov** [comment]
Thanks.
