### ISSUE TITLE
Infinite Zoom in MindMap-Module

### ISSUE THREAD

**Issue by ovalmartini** [dimkanovikov/KITScenarist#70]
The Infinite Zoom in the MindMap-Module should be prevented.

**Comment by dimkanovikov** [comment]
I agree

**Comment by dimkanovikov** [comment]
hmmm... Now I don't agree :) @ovalmartini why we need to prevent it?

**Comment by ovalmartini** [comment]
Because you could zoom out, scroll to a place, zoom in again and you are
faded away, so you cant come back to the root. I know, what you are
thinking, but may you can drop a "come back to the root"-button to the menu.

2017-02-21 6:23 GMT+01:00 Dimka <notifications@github.com>:

**Comment by dimkanovikov** [comment]
But it can contain more than one root node... Is this because of the scene much big? What, if we cut the scene and it will hold size equivalent to scheme size. Can this solution resolve the issue?

**Comment by ovalmartini** [comment]
This would be the best solution.

2017-02-23 11:16 GMT+01:00 Dimka <notifications@github.com>:
