### ISSUE TITLE
Информировать пользователя о попытке задвоения персонажа

### ISSUE THREAD

**Issue by ibogdanow** [dimkanovikov/KITScenarist#701]
Как рекомендация, в разделе "Разработка" добавить информационное сообщение, когда пользователь пытается добавить персонажа с именем, которое уже используется.

Сейчас, когда пользователь создает персонажа с уже использующимся именем, новый персонаж/двойник не создается. И пользователь может видеть только ранее созданный персонаж с таким именем.
Чтобы дать понять пользователю, что двойник не создан, а имеющийся персонаж с таким именем - это ранее созданный персонаж, можно выводить информационное сообщение. Например "Персонаж с таким именем уже существует".

**Comment by dimkanovikov** [comment]
Спасибо, улучшим.

**Comment by dimkanovikov** [comment]
duplicate #245
