### ISSUE TITLE
Selecting a card does not also select the corresponding scene in the script view.

### ISSUE THREAD

**Issue by johnblommers** [dimkanovikov/KITScenarist#705]
While using KITScenarist in dual-pane mode, select the cards module on the left and the script module on the right. Select a card. The script view does not scroll to the corresponding scene. We think it would be handy to have a preference so that both the card and the script module remain in sync - should the user wish it.

**Comment by dimkanovikov** [comment]
Thanks! Good find!

**Comment by dimkanovikov** [comment]
Will be implemented in the Starc.
