### ISSUE TITLE
Crashes when opening a specific Mind Map (Segmentation Fault) 0.7.1 rc 11

### ISSUE THREAD

**Issue by zfutures** [dimkanovikov/KITScenarist#707]
KIT crashes when I open a specific mind-map, I named "Flees" - it doesn't happen with the others. Sometimes it doesn't happen instantaneously, mostly after going back and forth between "Flees" and other-mind maps.

Also : When it crashes in night mode, it reopens in regular mode.

Kit 0.7.1 rc 11 on Debian 9.5

Bug Report attached.
[KitBug_Segmentation_Fault.txt](https://github.com/dimkanovikov/KITScenarist/files/2217910/KitBug_Segmentation_Fault.txt)

**Comment by dimkanovikov** [comment]
Hello @zfutures,

Thanks for your report. Looks like this bug was fixed in one of the beta versions. Can you check it with the latest beta?
