### ISSUE TITLE
Сделать тулзу для работы с дифами текстов проектов

### ISSUE THREAD

**Issue by dimkanovikov** [dimkanovikov/KITScenarist#718]
чтобы можно было сразу посмотреть диф из хэша, применить его к xml'ке и т.п.

**Comment by amaau** [comment]
#939 решило бы и эту задачу

**Comment by dimkanovikov** [comment]
О! Спасибо) эту тулзу я планировал для собственных технических нужд, и даже реализовал https://github.com/dimkanovikov/KITScenarist/tree/develop/src/devtools/patch-reader
