### ISSUE TITLE
Idea - Remover los nombres de los personajes en la exportación.

### ISSUE THREAD

**Issue by Scoppettuolo** [dimkanovikov/KITScenarist#818]
Podría ser genial para escribir novelas, y aún así mantener el orden que permite tener las referencias de los personajes mientras se va escribiendo, pero no mostrándolos en el producto final.

**Comment by dimkanovikov** [comment]
Hello @Scoppettuolo , we plan to add the ability to write novels in the future version 0.8.0. So all needed whistles and bells will be there.

**Comment by Scoppettuolo** [comment]
Eso es genial.

¿Va a ser compatible con la versión actual (...para seguir usando los personajes tal, y como hasta ahora...)?

**Comment by dimkanovikov** [comment]
Version 0.8.0 will be able to open projects created in 0.7.2, but 0.7.2 can't be able to open projects created in the 0.8.0.

**Comment by dimkanovikov** [comment]
Will be implemented in the Starc.
