### ISSUE TITLE
Build-ready tarball for packages

### ISSUE THREAD

**Issue by abenson** [dimkanovikov/KITScenarist#819]
Please provide a build-ready tarball (including git sub-modules) to make Linux packaging easier.

**Comment by dimkanovikov** [comment]
Hello, @abenson. For what packages do you want to use it? Why do not repackage it from .deb or .rpm package?

**Comment by abenson** [comment]
I was trying to package it for Void Linux, which prefers not to accept binary packages, which h repackaging Deb/rpm would be.

**Comment by dimkanovikov** [comment]
Looks like rpmextract tool can install apps from the rpm-packages. Did you try it?

**Comment by abenson** [comment]
Yes, I can take the pre-built RPM and extract it, but that won't meet muster for presumably an open source package.

**Comment by dimkanovikov** [comment]
Hmmm, Do you mean tarball with sources? If yes, then you can easily get it with this steps:
```
git clone https://github.com/dimkanovikov/KITScenarist
cd KITScenarist
git submodule update --init
```

**Comment by abenson** [comment]
~~~
git clone https://github.com/dimkanovikov/KITScenarist
~~~

This won't be accepted as it needs to be from a release tarball. 

~~~
git submodule update --init
~~~

This won't work from the release tarball, and in any case pulls an unversioned component which then can produce non-reproducable builds.

**Comment by dimkanovikov** [comment]
I think I got what you want. With the next release, I will provide archive with the sources to the release description here https://github.com/dimkanovikov/KITScenarist/releases

**Comment by abenson** [comment]
That's perfect! Thank you!

**Comment by AS383** [comment]
The same problem. Also the checking for missed sources would be great. Currently make produce many errors and build nothing forever.

**Comment by dimkanovikov** [comment]
The tarball for the next update can be found here - https://github.com/dimkanovikov/KITScenarist/releases/tag/0.7.2.rc9h
