### ISSUE TITLE
Error - Install KITScenarist 0.7.2 rc 8 on CentOS7.5

### ISSUE THREAD

**Issue by Spirit328** [dimkanovikov/KITScenarist#821]
When I tried to installl KITScenarist 0.7.2 on CentOS 7.5 via 

``rpm -i scenarist-0.7.2-rc8c.x86_64-en.rpm``

I got the following error messages: 
`` Error: Missing Dependencies:
	libQt5MultimediaWidgets.so.5()(64bit) is required by scenarist-0.7.2-rc8c.x86_64
	libqgsttools_p.so.1()(64bit) is required by s`cenarist-0.7.2-rc8c.x86_64``

Then I installed the following lib via 
``sudo yum install qt5-qtmultimedia ``
and re-run 
``rpm -i scenarist-0.7.2-rc8c.x86_64-en.rpm``

it went through.

Hope this helps someone

**Comment by dimkanovikov** [comment]
Thanks, @Spirit328! We will add this dependency to the package.

**Comment by alfasst** [comment]
I installed qt5-qtmultimedia via dnf (I use fedora29). Still I get the same error.

**Comment by dimkanovikov** [comment]
@alfasst On the latest Fedora, we have some other issues, so need some time to the exploration of how we can fix it.

**Comment by yury-SB** [comment]
@Spirit328 
Is it still actual? In RC9J ?
