### ISSUE TITLE
Цвет шрифта при сохранении отчёта по репликам персонажей в файл в тёмной теме

### ISSUE THREAD

**Issue by giryaev** [dimkanovikov/KITScenarist#832]
Если в настройках включена тёмная тема, то при нажатии на «Сохранить отчёт в файл» в «Статистика>Реплики персонажей», формируется PDF с белым фоном и бледно-серым (близком к белому) текстом. 
При переключении на светлую тему — всё хорошо — текст выводится тёмным цветом.

ОС: macOS 10.15 (19A512f)

**Comment by dimkanovikov** [comment]
Спасибо, уже поправлено. Выйдет в грядущем обновлении.

Дубликат #825
