### ISSUE TITLE
Please make update URL optional

### ISSUE THREAD

**Issue by yurivict** [dimkanovikov/KITScenarist#834]
See ```StartUpManager::makeUpdateUrl```.
On some systems all software is installed from packages, and there is no need to try finding updates online. Please add the build option to disable such updates.

FreeBSD 12 amd64

**Comment by dimkanovikov** [comment]
Since our main distributing option is a direct install, it is valuable for us to the app can manually check availability of it's updates.

**Comment by ghost** [comment]
Достаточно обрамить код проверки обновления в `##ifndef DONT_CHECK_UPDATE` ... `#endif`, что никак не отразиться на ваших сборках, а сопроводителям пакетов для Unix-like систем позволит отключать его. Всё равно у программы, запускаемой от пользователя, нет доступа на запись в системные директории.
