### ISSUE TITLE
The project doesn't install anything.

### ISSUE THREAD

**Issue by yurivict** [dimkanovikov/KITScenarist#835]
Please see how Arch linux has to install it manually: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=scenarist

Please add the 'install' target.

**Comment by dimkanovikov** [comment]
Pull request will be a great starting point.

**Comment by yurivict** [comment]
I'm a volunteer package maintainer, I maintain 900+ packages. If every package upstream would ask me to submit a pull request this would become more than a full-time job.

**Comment by cyrant** [comment]
Для справки: [https://doc.qt.io/qt-5/qmake-advanced-usage.html#installing-files](https://doc.qt.io/qt-5/qmake-advanced-usage.html#installing-files)

**Comment by yury-SB** [comment]
We will think about after ci/cd implementation.
