### ISSUE TITLE
Добавьте возможность распечатывать ЦВЕТНЫЕ карточки.

### ISSUE THREAD

**Issue by MarinIgor** [dimkanovikov/KITScenarist#836]
Приветствую! Сейчас в КИТ сценарист есть возможность печатать карточки только в ч/б варианте. Это лишает половины возможностей работы с карточками, поскольку, именно возможность работать с цветными карточками делает работу удобной и понятной. Сейчас нельзя просто распечатать те карточки, которые создал в КИТ сценаристе на цветном принтере и прикрепить их себе на доску. Можно только ч/б. Появится ли такая возможность?

**Comment by dimkanovikov** [comment]
отличная идея! добавим в одном из будущих обновлений
