### ISSUE TITLE
Very small text in the Research sections

### ISSUE THREAD

**Issue by lycollicott** [dimkanovikov/KITScenarist#838]
Maybe I'm just not using it correctly, but whenever I write log lines, synopsis or character descriptions the text displayed on screen is very, very small and hard to read.
<img width="491" alt="Screen Shot 2019-08-03 at 5 29 08 PM" src="https://user-images.githubusercontent.com/43612842/62416635-c4457c00-b614-11e9-9455-a90adfd54bc9.png">

**Comment by dimkanovikov** [comment]
Hello @lycollicott, you need to scale up text. Use Ctrl+ if you on Windows or Linux, or Command+ if you on Mac.
