### ISSUE TITLE
Bad translations on website

### ISSUE THREAD

**Issue by its-danny** [dimkanovikov/KITScenarist#839]
There's some iffy translations going on, but this one stuck out to me: **What we will can through month**

I think it's supposed to be a roadmap? Should probably something like: **Roadmap for this month | 3 Months | 1 Year**

--

Also, **WE ARE NOW AND WE ARE ~IN~ THE FUTURE**

**Comment by its-danny** [comment]
The website itself doesn't seem to be open source, but if it was I wouldn't mind going through and fixing what I can find.

**Comment by dimkanovikov** [comment]
Thanks. I fixed the issues you mention. I can't give you access to the site itself, but can send you files with content from the main pages, so, you can help us to correct our bad English :)

**Comment by yury-SB** [comment]
Text not found.
