### ISSUE TITLE
KIT Scenarist name?

### ISSUE THREAD

**Issue by TheLizardfolk** [dimkanovikov/KITScenarist#841]
Hello, the name in English seems a little off to me.  I've seen your mascot as a Screenwriting Cat and "KIT" and "Scenarist" could make a pretty playful pun in the English language if it's named as "Scenarist KIT" because those two words in that order could either mean your mascot (a screenwriting cat) or a screenwriter kit (like a screenwriter's toolbox).

I know it seems you've set on your software's branding as "KIT Scenarist" but if you see my point above, perhaps you may consider changing it to Scenarist KIT to market to English speakers better as they'd get the playful pun of "Scenarist KIT" better if the words are in that order.

Just a thought!  Been enjoying your software a lot so far!

**Comment by dimkanovikov** [comment]
Hello, my friend. Thanks for your suggestion. Currently, KIT Scenarist is a just a transliteration of our Russian name "КИТ Сценарист", where КИТ|KIT is a reduction of the Cinema And Television. I understand that the current name looks strange for English speaking people and for the future update I think about rebranding. We will change the name to something more simple :)

**Comment by TheLizardfolk** [comment]
Ah ha, gotcha, thanks for the clarification.  If it means anything, I like Scenarist and KIT as words, I think they pair well together too.
