### ISSUE TITLE
Audio Drama Formats Support

### ISSUE THREAD

**Issue by TheLizardfolk** [dimkanovikov/KITScenarist#842]
Any plans to support the two Audio Drama formats in the near future?  There's two major ones that Audio Drama writers write in that's the US Radio format and the BBC Format.  I've attached both.  Audio Drama writers don't have a lot of software options for their specific formats so I was hoping KIT could be one I'd rely on that can do both formats accurately.

[US Radio Format.pdf](https://github.com/dimkanovikov/KITScenarist/files/3528282/US.Radio.Format.pdf)
[BBC Scene Format.pdf](https://github.com/dimkanovikov/KITScenarist/files/3528283/BBC.Scene.Format.pdf)

**Comment by JohnGaines** [comment]
^seconded. I'd love to be able to write in the US and BBC audio drama formats. I could use this in my daily writing and would suggest KIT to others.

**Comment by dimkanovikov** [comment]
Hey guys, plan to add it in one of the next big updates.

**Comment by TheLizardfolk** [comment]
Thanks, that would be super great.  There isn't a software that supports the US Radio format and only a very small handful supports the BBC Format.  So I would love to just use your software to have one option to do Screenplay, US Radio Format, and BBC Format and not juggle multiple options.

**Comment by yury-SB** [comment]
Thanks, @TheLizardfolk 

It is in roadmap of the KIT`s next generation - Story Achitect https://starc.app/ after it will be ready for everyday writer work.
