### ISSUE TITLE
Scenarist does not open after crashing on Windows

### ISSUE THREAD

**Issue by DanielOaks** [dimkanovikov/KITScenarist#850]
Hi there! I've been loving KIT Scenarist, great program. But I've got a problem with it on Windows (on macOS the same problem doesn't happen).

Sometimes KIT will crash randomly when I alt+tab to another program and then alt+tab back to KIT. After force-quitting the program with task manager KIT won't open again. It's listed in task manager and uses CPU, but no window is displayed.

This screenshot is after KIT crashed, I force-quit it, and then I tried opening KIT again three times (both the installed version and the portable version, same result).

![image](https://user-images.githubusercontent.com/251281/65399378-9eac4600-ddff-11e9-888d-f5c80d7b8cfd.png)

Is there any debug log I could enable to see what's going on better? I'll see if I can get Qt compiling to work otherwise, no worries. Thanks for the cool program!

**Comment by dimkanovikov** [comment]
Hello @DanielOaks,

Is this issue happened on the concrete editor (script or cards) or not depends on the editor? No, there is no debug log. I can suggest you try next - rename Windows Registry entry HKEY_CURRENT_USER/Software/DimkaNovikov labs./Scenarist and try to restart the app. Does the issue still happen?

**Comment by DanielOaks** [comment]
Hi dimkanovikov!

This issue happened on the Script page. Thank you, I have tried that and the issue still happens after renaming the registry entry and then restarting the app. Only restarting my computer lets me open the app again.
![image](https://user-images.githubusercontent.com/251281/65515904-600fac00-df23-11e9-987e-2ffa6ea6e377.png)

I think it might be my machine and Qt not working together nicely, I've been using Qt Creator and a very similar issue happens with it too. I will look into it more on my side, thanks for the help :)

**Comment by dimkanovikov** [comment]
I see. Okay, I wish you good luck with fixing it! :)
