### ISSUE TITLE
just sharing an experience

### ISSUE THREAD

**Issue by cristianochs** [dimkanovikov/KITScenarist#856]
Hello my name is Cristiano and I am from Brazil / Rio de Janeiro. I love KITScenarist and wish I could share a little recent frustration.

Unfortunately your software is not working on DEBIAN 10.1, neither under WAYLAND nor under XORG.
Also does not work on fedora 30. In mageia when trying to install the installer detects two dependencies and I can not solve them with DNF.

I can only use your software under UBUNTU 18.04 LTS. It's beautiful software and I wish I could change distribution if UBUNTU fails to work for me.

**Comment by yury-SB** [comment]
We will think about after ci/cd implementation.
