### ISSUE TITLE
Bug on project cloud sharing

### ISSUE THREAD

**Issue by Reihtul** [dimkanovikov/KITScenarist#858]
Hi,

I've created a new project in cloud from the smartphone App (Android). I started writing it, and it works well on the phone as you can see on this screenshot:

![Screenshot_20191026_191440_pro dimkanovikov kit scenarist](https://user-images.githubusercontent.com/53254106/67623768-7f06a400-f829-11e9-9789-ba34efdd5462.jpg)

(Yes I know, bad writing in french, please ignore this is not the point :-D)

Now when I open it in my PC (Windows) I get only that bizarre thing on scenario page:

![Capture](https://user-images.githubusercontent.com/53254106/67623773-86c64880-f829-11e9-82f2-7f5feca0e269.PNG)

Same thing when I open it on another smartphone (not the one from were I created the project) but still an Android:

![Screenshot_20191026-191401_Scenarist](https://user-images.githubusercontent.com/53254106/67623777-904fb080-f829-11e9-8842-4adacdfdc9b2.jpg)

When I come back to the first smartphone (the one from which I created the project) all is still Ok as in the first screenshot.

=> I managed to fix the problem by this way: from the first smatphone (the one where project were created and is functionnal) I selected menu/share and sent to myself the .kitsp by email. On my PC I created a new project in cloud and imported that .kitsp. Now that new project is Ok from wherever I access it (my PC and the two smartphones).

Neverthelesse, there were a bug here!

**Comment by dimkanovikov** [comment]
Hello, my friend. Thanks! Android app is outdated a bit (I'm sorry for this). Plan to publish update in the November in which this issue will be fixed.

**Comment by dimkanovikov** [comment]
Android app was updated, so, now it should work fine.
