### ISSUE TITLE
Program won't open in Mac OS Catalina

### ISSUE THREAD

**Issue by harley-meya** [dimkanovikov/KITScenarist#859]
I downloaded this version: `scenarist-setup-0.7.2.rc9e_en.dmg` and installed it on a 2017 MacBook Pro running Catalina, but get the following error when I try to run the program:

<img width="416" alt="Screen Shot 2019-10-31 at 3 17 50 PM" src="https://user-images.githubusercontent.com/33461231/67979036-dd4cd180-fbf1-11e9-8ccf-41e4b9de1e11.png">

It does work on my other computer running Mojave, so it must be an issue specific to Catalina.

**Comment by dimkanovikov** [comment]
Thanks. Yeah, it's Catalina specific issue, we need notarize tha app. Will do it for the next update.

**Comment by dimkanovikov** [comment]
Catalina ready update will be published tomorrow
