### ISSUE TITLE
Разработать систему автоматических обновлений программы

### ISSUE THREAD

**Issue by dimkanovikov** [dimkanovikov/KITScenarist#86]

**Comment by kaynix** [comment]
как насчет добавить програму в репозиторий Убунти/Дебиана ?

**Comment by dimkanovikov** [comment]
Дело в том, что нам нужна более гибкая система обновлений:
во-первых она должна поддерживать и Linux, и Windows, и Mac OS X - хорошо, для Linux'а и для Mac'а есть способ, а как быть с WIndows? Что на счёт других дистрибутивов Linux? Всё равно придётся делать;
во-вторых там будет 2 типа обновлений - для тех кто пользуется бета-версиями и для тех, кто работает только со стабильными версиями;
В третьих, если размещать обновления в том же Mac App Store, то пользователям придётся ждать ещё какое-то время, пока обновление пройдёт вместо того, чтобы сразу его установить.
И в четвёртых, в свежих версиях, в программе могут быть использованы возможности из свежей версии Qt, которая ещё не входит в репозиторий, непонятно как быть в таком случае.

Вариант размещения программы в репозитории я рассматриваю скорее как дополнительный способ.

**Comment by Armijo38** [comment]
Предлагаю сделать следующее.
Визуально выглядит как обновления в телеграме Т.е. появился апдейт - в программе ненавязчиво мигает кнопка "Update". Пользователь нажимает на нее - программа закрывается и запускается новая версия (все что надо было скачать и установить - скачалось и установилось еще до того, как кнопка начала мигать). Или пользователь просто закрывает и открывает приложение. В этом случае все равно запускается новая версия.

Реализацию предлагаю обсудить позже :)

**Comment by dimkanovikov** [comment]
Если честно, то я против такой концепции в данном приложении. Дело в том, что авторы и так очень боятся, что их тексты может кто-то взять, и, если они увидят, что что-то происходит автоматически - без их ведома, то это может сыграть против нас в плане доверия. Я бы предложил показывать страницу, которая будет занимать весь интерфейс и в ней будет что-нибудь типа кнопок "установить/пропустить обновление", нажимаешь и скачивается обновление и устанавливается. Опять же надо подумать, может быть лучше запускать стандарный установщик для каждой системы, или делать обновление вручную, подменяя исполняемый файл... Я лично больше склонен к варианту с локальным установщиком, чтобы после обновления, программа писала: "после нажатия кнопки установить, программа будет закрыта и будет запущена установка новой версии." и одна кнопка - "Установить". После чего запускается стандартный для текущей системы процесс установки/обновления программы.
