### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by ghost** [dimkanovikov/KITScenarist#879]
### Request for 3 new features:
- a thesaurus for major languages 
- a storyline (like in final draft)
- script breakdown features 

It might be easier for international contributors if the issues are in English.

**Comment by yury-SB** [comment]
Thanks, @Mikhail-Zex 

We will think about it in the next KIT`s generation - Story Achitect https://starc.app/ after it will be ready for everyday writer work.

**Comment by ghost** [comment]
Cool.

**Comment by ghost** [comment]
Is starc a web app?

**Comment by yury-SB** [comment]
It is device based. Desktop and mobile apps like the KIT.
