### ISSUE TITLE
Translation German Ordener statt Ordner

### ISSUE THREAD

**Issue by KeyTamer** [dimkanovikov/KITScenarist#883]
![Bildschirmfoto vom 2020-04-27 20-59-46](https://user-images.githubusercontent.com/29024729/80409992-14aee900-88ca-11ea-8758-8f7f793fa47a.png)

**Comment by dimkanovikov** [comment]
Hello, my friend. I can't find any occurrences of the word "Ordener" in the German translation. On your screenshot, I see the "Ordner" word, which seems correct if we can trust google translate :)
