### ISSUE TITLE
Ctrl+C приводит к вырезанию фрагмента текста в облаке

### ISSUE THREAD

**Issue by yury-SB** [dimkanovikov/KITScenarist#885]
**Шаги воспроизведения:**
1. Открыть файл Смерть из багажника.kitsp
2. Найти и выделить фрагмент текста, указанный на скриншоте 
начало 
> У Оленевой проблема с компом. 

окончание 
> несколько четких кадров.  
3. Нажать Ctrl+C 
_Ожидаемый результат._
Происходит копирование фрагмента текста.
_Фактический результат._
Указанный фрагмент текста вырезается.

На текущий момент баг устойчиво воспроизводится только с указанным фрагментом текста. При использовании контекстного меню (ПКМ) - не воспроизводится.

**Окружение**
Windows 10 Pro x64 
Версия 1909 (Сборка ОС 18363.778)
KIT Scenarist 0.7.2 rc9h
Логины облака, на которых воспроизводится баг: mail@yury4you.ru,  test@yury4you.ru
Файл с ошибкой: ... Смерть из багажника.kitsp
Файл без ошибки: ... Смерть из багажника_000.kitsp (копия предыдущего через импорт проекта)

Доступ к облаку и нужным файлам предоставлен на support@kitscenarist.ru

![2020-04-28_08-36-48](https://user-images.githubusercontent.com/46703960/80451201-e661f580-892b-11ea-8bff-139c19ce72b3.png)

**Comment by dimkanovikov** [comment]
@yury-SB не получается воспроизвести, ни в WIndows, ни в Linux.

**Comment by dimkanovikov** [comment]
@yury-SB up!

**Comment by dimkanovikov** [comment]
не воспроизводится
