### ISSUE TITLE
PDF Export with page numbers enabled skips first page

### ISSUE THREAD

**Issue by polymetric** [dimkanovikov/KITScenarist#886]
My PDF export settings are as follows:
```
Format: PDF
Additional: (Numbering, Title Page etc.): Yes
Template: Final Draft Screenplay (Letter)
Print Title Page: No
Print Page Numbers: Yes
Print Scene Numbers: No
Print Speaking Parts count: No
Save Review Marks: No
Check Page Breaks: Yes
Print Watermark: No
```
My script is four pages long. The second, third, and fourth pages have page numbers, as expected. The first page, however, has no page number. Title page and scene numbers are disabled.

**Comment by dimkanovikov** [comment]
This is not a bug, it's a standard requirement of the screenplay formatting.

https://screenwriting.io/what-is-standard-screenplay-format/

> Pages should be numbered in the top right corner, flush to the right margin, a half-inch from the top of the page. Numbers should be followed by a period. The first page is not numbered. The title page is neither numbered nor does it count as page one, so the first page to have a number is the second page of the screenplay (third sheet of paper, including the title page), which is numbered 2.

**Comment by polymetric** [comment]
Ah, never knew that.
It still may be a good idea to add that option in the template editor, because some script formats may not have that clause.

**Comment by yury-SB** [comment]
Thanks, @polymetric 

We will return to it in the next KIT`s generation - Story Achitect https://starc.app/ after it will be ready for everyday writer work.
