### ISSUE TITLE
SAVING bUG/ ISSUE

### ISSUE THREAD

**Issue by sutharsanank** [dimkanovikov/KITScenarist#887]
When i save the project this things comes ...
<img width="960" alt="saving bug kit scenarist" src="https://user-images.githubusercontent.com/65469714/82262184-12e2bd80-997e-11ea-8a94-8160462daef8.png">

**Comment by dimkanovikov** [comment]
Hello @sutharsanank. Does it happen with each project or with a concrete one?

**Comment by dimkanovikov** [comment]
@sutharsanank any updates on this issue?

**Comment by sutharsanank** [comment]
Dear sir,
              Kindly check the Mindmap session,, Iam not able to properly
utilize it since its not linking with other nodes when removed from parent
node
