### ISSUE TITLE
Incomplete dependencies for the `.deb` packages

### ISSUE THREAD

**Issue by lenormf** [dimkanovikov/KITScenarist#888]
Hi,

I installed the x64 `.deb` package in a minimal Debian Buster environment (Docker image), and had to install the following packages to get the program to run:

```
libpulse-mainloop-glib0 libnss3 libasound2 libegl1-mesa
libxss1 libgl1-mesa-glx libxslt1.1 libsm6 libxkbcommon-x11-0 libxcb-icccm4
libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0
```

Note that not all the above packages might be required, I just install all of these by default when running Qt applications in containers.

HTH.

**Comment by dimkanovikov** [comment]
Thanks, will check it

**Comment by dimkanovikov** [comment]
Qt binaries will be removed from the package, plus I'd update the control-file. Now it has correct dependencies inside.
