### ISSUE TITLE
Locating "orphans" in the output

### ISSUE THREAD

**Issue by lenormf** [dimkanovikov/KITScenarist#889]
Hi,

A feature that would be interesting to have and that no other software implements (as far as I know) is locating "orphans" in the resulting screenplay.

Orphans are lines on which there's a single word, and nothing else, e.g.

```
This is a long action token with a single trailing
word.
```

In the above, "word" is the orphan.

Making the sentence shorter (somehow, if possible/relevant) would allow the screenplay output file to be slightly shorter, because a line would be saved. Find all orphans, fix them, and suddenly the screenplay is 5 pages shorter - good.

It'd be convenient to have Scenarist find all orphans automatically, and allow jumping to them.

Thanks!

**Comment by dimkanovikov** [comment]
Good idea!

**Comment by yury-SB** [comment]
Thanks, @lenormf 

We will think about it in the next KIT`s generation - Story Achitect https://starc.app/ after it will be ready for everyday writer work.
