### ISSUE TITLE
The package version of the `0.7.2.rc9h` is still `0.7.2.rc9f`

### ISSUE THREAD

**Issue by lenormf** [dimkanovikov/KITScenarist#890]
Reproducer:

- download https://kitscenarist.ru/downloads/linux/scenarist-setup-0.7.2.rc9h_en_amd64.deb
- install the package
- the package version is incorrect:

```
Unpacking scenarist (0.7.2.rc9f) ...
Setting up scenarist (0.7.2.rc9f) ...
```

HTH.

**Comment by dimkanovikov** [comment]
Thanks!

**Comment by dimkanovikov** [comment]
it will be corrected with next update
