### ISSUE TITLE
Using Scenarist as FDX editor / open by file extension

### ISSUE THREAD

**Issue by hybridherbst** [dimkanovikov/KITScenarist#891]
We're using KITScenarist mainly as an FDX editor right now. This means that we don't actually use the kitsp file format, but always import FDX and then export FDX again.

This works pretty well, but all kinds of weird things happen when trying to connect the .fdx extension with KITScenarist:
(1) connect fdx extension to KITScenarist so that it should be opened with it
(2) double-click fdx file
(3) Scenarist opens, shows correct filename, but no content
![image](https://user-images.githubusercontent.com/2693840/82665646-8a417700-9c34-11ea-86e2-99459b2313f1.png)
(4) Import fdx file - looks ok
(5) when changing focus or saving, error appears:
![image](https://user-images.githubusercontent.com/2693840/82665707-a80edc00-9c34-11ea-8c76-c25b21f203ab.png)

It seems that it tries to load the FDX as kitsp database and fails.

A good approach might be to:
- when scenarist is called with fdx file as parameter, create temp database and import fdx into it, and remember that initial file was fdx
- when user tries to save, ask if they want to save the fdx or kitsp (and that some data can only be saved in kitsp) - this would be similar to what e.g. Photoshop does when editing JPGs or PNGs (and not PSDs).

I guess this issue here is part bug (shouldn't try to open wrong file as database and shouldn't try saving into it) and part feature request (allow opening fdx files directly with KITScenarist).

**Comment by dimkanovikov** [comment]
Thanks! Good idea!

**Comment by hybridherbst** [comment]
Cool! Looking forward to trying it out :)

**Comment by dimkanovikov** [comment]
Added checking for opened file extension and for database opening errors.

**Comment by dimkanovikov** [comment]
Ability to open custom files, importing and resaving them back added to Story Architect backlog :)

**Comment by hybridherbst** [comment]
Nice, thank you. Do you have a rough ETA (days, weeks, months, years) just so I know to look out for it?

**Comment by dimkanovikov** [comment]
Plan to publish update on the end of this week.

**Comment by hybridherbst** [comment]
Oh I meant for the
> Ability to open custom files, importing and resaving them back added to Story Architect backlog :)

**Comment by dimkanovikov** [comment]
Ah, the only God knows this :) it's an interesting option, but it has a lot of side effects for users, which not so simple to sort. For example, what if the user opened fdx file then want to add a description of the character, or want to create a document in the research section? We need to think a lot about this functionality and about how we can implement it with a minimum headache for us and for users.
