### ISSUE TITLE
For how long will this project still be maintained?

### ISSUE THREAD

**Issue by lenormf** [dimkanovikov/KITScenarist#894]
Hi,

There are 300 issues, no visible work done on this project, and apparently another project superseeding this one is in progress.

Is Scenarist still maintained? If yes, will it still be when the other story-telling software is released?

Thanks!

**Comment by lenormf** [comment]
https://kitscenarist.ru/en/history.html

>KIT will get a couple more updates fixing some critical errors and adding new localizations. As soon as STARC can functionally replace KIT its further development will be postponed, though the app itself will remain available for installation and use.

I guess the question is now *when* will Scenarist become obsolete)

**Comment by dimkanovikov** [comment]
It's a question for me too :)

**Comment by lenormf** [comment]
Let's just say that when you know, you'll update the site/README. In the meantime, no need to leave this open.

Thanks for keeping the project alive!

**Comment by dimkanovikov** [comment]
Yup. Plus, I'll add a link to the next project repo :)
