### ISSUE TITLE
Ubuntu 20.04: application crashes on attempt to open screenplay editor

### ISSUE THREAD

**Issue by M-Beliaev** [dimkanovikov/KITScenarist#905]
Hello!
I've got a problem with using KITScenarist in **Ubuntu 20.04**. When I try to get to the screenplay editor in any project, the application just swaps off. No error reports, no anything. So the most important feature of the application is impossible to use.
I don't know what additional information is required to solve this problem, so please, request anything that is needed and will provide what I can.
**Thank you!**

**Comment by dimkanovikov** [comment]
Hey! 64bit package?

**Comment by M-Beliaev** [comment]
> Hey! 64bit package?

Hello! 64bit one, Indeed!

**Comment by dimkanovikov** [comment]
Please, recheck it now. But firstly you need to remove previously installed package, because version number keeps the same and package manager can skip installation process.

**Comment by M-Beliaev** [comment]
> Please, recheck it now. But firstly you need to remove previously installed package, because version number keeps the same and package manager can skip installation process.

Looks like it's fixed alright!
Thank you!
