### ISSUE TITLE
New Template Formatting Error

### ISSUE THREAD

**Issue by ghost** [dimkanovikov/KITScenarist#907]
I made a new template for a novel manuscript consisting of:
- centered scene heading[as chapter title]
- action [as chapter text]

The manuscript is formatted properly within the script editor but when exporting the file and/or print previewing it, the default 'Final Draft formatting is used'.

The option to rename script units (eg. option to rename 'scene heading' to 'Chapter title' would be very helpful)

I'm adding a few pictures below for clarity.
![formatting 1](https://user-images.githubusercontent.com/52100648/87873522-07f4db00-c977-11ea-9f59-b10d6dc2a76e.jpg)
![formatting 2](https://user-images.githubusercontent.com/52100648/87873524-09be9e80-c977-11ea-93e6-cdf7f354780e.jpg)
![formatting 3](https://user-images.githubusercontent.com/52100648/87873516-01666380-c977-11ea-9a20-774fcebd8426.jpg)

**Comment by dimkanovikov** [comment]
You need to setup your own template for export too. Check out advanced export options.

**Comment by ghost** [comment]
Ok, will do. Thanks.

**Comment by ghost** [comment]
where can i find 'advanced export' options, i've looked around a bit, haven't found it yet.

**Comment by dimkanovikov** [comment]
Menu -> Export -> Export Script -> Additonal (Numbering, Title page, etc.) checkbox -> Template

**Comment by ghost** [comment]
It'd be easier for users if you made that option the default for the applied template instead of them having to select the option after a bit of searching. Either ways Thanks a lot. 😁

**Comment by dimkanovikov** [comment]
I agree with your point. It is not trivial in some keys. I will think about how to improve it.
