### ISSUE TITLE
KITScenarist crashing on Ubuntu 20.04

### ISSUE THREAD

**Issue by johnygum** [dimkanovikov/KITScenarist#909]
I just installed KITScenarist on my Ubuntu 20.04 laptop and when I create a new project and try to edit synopsis or logline or script or add characters, the program just closes. When I run it from terminal, this is what it says:
`OpenType support missing for "Ubuntu", script 17`
`QPainter::begin: Paint device returned engine == 0, type: 2`
`QWidget::render: Cannot render with an inactive painter`
`Segmentation fault (core dumped)`

**Comment by dimkanovikov** [comment]
Hello, my friend. It was a problem with the installer and we upload a new one to the site. Please reload it and reinstall, but firstly remove previously installed version, to package manager can correctly install a new package.

**Comment by johnygum** [comment]
It's working now! Thank you very much!

**Comment by dimkanovikov** [comment]
:+1:
