### ISSUE TITLE
Spellcheck flags certain contractions if the wrong type of apostrophe is used. ( ’ vs ' ) -- English language

### ISSUE THREAD

**Issue by ocalhoun6** [dimkanovikov/KITScenarist#911]
Minor bug. This is mainly an issue after importing a file or pasting text from elsewhere, since Scenarist automatically uses what its spellchecker determines to be the correct type when typing.

The spellchecker will flag certain contractions (like "I've", "you've", and "doesn't") if the wrong type of apostrophe is used. It only flags part of the word. In "I've" and "You've", it flags the "ve". In "Doesn't" it flags the "Doesn". It's obviously treating the parts that come before and after the apostrophe as separate words.

It does this if angled apostrophes ( ’ -- `unicode U+2019`) are used. Straight apostrophes like Scenarist defaults to ( ' -- `unicode U+0027`) work as expected.
Example: "You’ve" will be flagged as a spelling error, while "You've" will not.
But when text is imported from elsewhere, it may be from software that defaults to angled apostrophes. (Final Draft 9 does this.)

In most other spellcheckers I've experimented with, the spellchecker will accept either type of apostrophe without complaint.

A workaround is to add things like "Doesn" to the user's custom dictionary, but that's not a perfect solution. In the case of "ve", I could not get the context menu for spelling errors to open on the word (perhaps because it was only two letters?) and therefore I couldn't add it to my custom dictionary. I actually had to go find the dictionary file, open it in a text editor, and manually add a line in it for "ve".

Obviously, it would be better if the English spellchecker could recognize and allow angled apostrophes when used in contractions.

**Comment by dimkanovikov** [comment]
Thanks, it will be fixed.
