### ISSUE TITLE
[Feature Request] Import Anki cards

### ISSUE THREAD

**Issue by sunjam** [dimkanovikov/KITScenarist#914]
Hi, loving the software.  It'd be really useful to be able to import cards from [Anki](https://forums.ankiweb.net/), a fully open source flash card system available on all platforms (Mac, Windows, Linux, iOS, Android).  Here is the [documentation page](https://docs.ankiweb.net/#/).  Thanks for considering either way!

[Cards are exported as text or in a couple formats](https://docs.ankiweb.net/#/exporting).

> Deck (.apkg) packages contain a single deck (and any child decks it may have). They have a filename ending with .apkg, but a filename other than collection.apkg. When you import a deck package, Anki will add the contents into your collection, rather than overwriting your collection.

> If you choose “Notes in Plain Text”, Anki will write the contents of the notes into a text file. Each field is separated by a tab. If you edit the resulting file and don’t modify the first field, you can later import that file back into Anki and Anki will update your notes based on your edits, provided you import back into the same note type.  In order for formatting to be preserved when you import text back in, the text is exported with all the HTML formatting embedded in it.

**Comment by yury-SB** [comment]
Thanks, @sunjam 

We will think about it in the next KIT`s generation - Story Achitect https://starc.app/ after it will be ready for everyday writer work.

**Comment by dimkanovikov** [comment]
Hello, @sunjam can you share your use case of how you want to work with this feature?
