### ISSUE TITLE
Unable to delete Card until i closed my project and reopened it

### ISSUE THREAD

**Issue by NavpreetDevpuri** [dimkanovikov/KITScenarist#915]
In windows 10,
I rearranged cards 
I was writing basic scripts and I change locations names multiple times and changed some character's names too.
I noticed after changing locations names the changed locations in cards as new cards and the previous unchanged locations are also there and when I tried to delete unchanged locations and it did not work and after that, I closed the software and when I reopened it the problem solved.

after that, I tried but unable to recreate the same issue again maybe I did something strange that makes the software fail. Someone may think about it. it may happen in the future too.

**Comment by yury-SB** [comment]
Hello, friend!

We know about this issue. We still can`t localize that floating bug.
If you will facing it again - just restart your app and continue your work. If you will find a stable way to reproduce it - write to us again or reopen this issue.

Thanks!
