### ISSUE TITLE
Is there any way to do dual dialog in Scenarist?

### ISSUE THREAD

**Issue by ocalhoun6** [dimkanovikov/KITScenarist#917]
Does Scenarist have any way to do dual dialog? Like this example:

![eo8sflt7yp841](https://user-images.githubusercontent.com/26573303/92076686-d6da3980-ed6f-11ea-9557-acb615dd5520.png)

If there is, I can't find it, and it should probably be added. It's not the kind of thing you'd use often, but when you do need it, nothing else will do.

I've also noticed that if dual dialog exists in a script you import from Final Draft, it just gets replaced by >> symbols, completely losing the text of the dialog.

**Comment by yury-SB** [comment]
It is released in the next KIT`s generation - Story Achitect https://starc.app/.
