### ISSUE TITLE
Сохранение информации для авторизации

### ISSUE THREAD

**Issue by Armijo38** [dimkanovikov/KITScenarist#92]
Сейчас email и пароль для автологина сохраняются так, что при необходимости их можно восстановить. предлагается следующее
1. Отказаться от сохранения email и пароля. Вместо них хранить ключ сессии
2. Перенести хранение токена в отведенное для этого место (keychain - macOS, kwallet - KDE, gnome-keyring - gnome, xfce)

**Comment by dimkanovikov** [comment]
А как пароль будет храниться на WIndows, Android, iOS?

**Comment by Armijo38** [comment]
в Android и iOS тоже есть хранилище. В Windows его, к сожалению, нет. Придется использовать существующее решение

**Comment by dimkanovikov** [comment]
Хорошо.

**Comment by dimkanovikov** [comment]
https://github.com/frankosterfeld/qtkeychain

**Comment by dimkanovikov** [comment]
Will be implemented in Starc.
