### ISSUE TITLE
Missing blank line between a dialogue and an action next to the dualogue in .docx exported file when the action is on first line of next page.

### ISSUE THREAD

**Issue by NavpreetDevpuri** [dimkanovikov/KITScenarist#921]
it happens when action is on the next page in script in KITScenarist software but after export the .docx file its may become together I mean the dialogue and the action may come on the same page due to difference in font size, in that case, it is missing the space between the dialogue and the action in .docx.

it is more like a coincidental error.

**Comment by yury-SB** [comment]
Thanks, @NavpreetDevpuri

We will think about it in the next KIT`s generation - Story Achitect https://starc.app/ after it will be ready for everyday writer work.

**Comment by dimkanovikov** [comment]
same as #923

**Comment by NavpreetDevpuri** [comment]
> same as #923

let me explain it with an example look at the following example 
When a dialogue is at the end of a page and the action is on the next page 
then It combines the dialogue with the action. 

AND I DID NOT EVEN EDIT THE .DOC FILE IT JUST HAPPENS DUE TO MISSING NEWLINE BETWEEN DIALOGUE AND ACTION

https://github.com/dimkanovikov/KITScenarist/issues/924#issuecomment-721099965

**Comment by dimkanovikov** [comment]
what font do you use?

**Comment by NavpreetDevpuri** [comment]
> what font do you use?

default fonts, I don't change fonts. 
I think in KIT the default font is `Courier Prime` as I noticed.

**Comment by NavpreetDevpuri** [comment]
I am failing to replicate that

**Comment by NavpreetDevpuri** [comment]
Found another strange behavior, 
It's ignoring two lines
![NDSMywWmfc](https://user-images.githubusercontent.com/30471072/98019344-a2463500-1e27-11eb-8cc9-db7322d4fee3.gif)

**Comment by dimkanovikov** [comment]
> Found another strange behavior,

There is a footer of the page, so it ignored on import.
