### ISSUE TITLE
While importing/exporting scrript as .docx file, take care about (MORE) and (CONT'D).

### ISSUE THREAD

**Issue by NavpreetDevpuri** [dimkanovikov/KITScenarist#923]
(MORE) represents that the dialogue is continuing on the next page.

While exporting the .docx file then due to the font size difference its should adjust the (MORE) and (CONT'D) accourding to .docx not just according to the script in KITScenarist

while importing .docx it takes (MORE) as a new character.

**Comment by dimkanovikov** [comment]
It relates to the fonts you use and it impossible to do if you use nonstandard, or not installed in your system font.

**Comment by NavpreetDevpuri** [comment]
After importing the script it creates the following problem 
(MORE) is not a character and it is importing it as a character.
![Scenarist_FZRDvyzRtv](https://user-images.githubusercontent.com/30471072/97988081-68af0300-1e02-11eb-8ab3-3cc24aec7e84.png)
