### ISSUE TITLE
Idea - Use Google Docs to collaborate

### ISSUE THREAD

**Issue by NavpreetDevpuri** [dimkanovikov/KITScenarist#925]
After resolving https://github.com/dimkanovikov/KITScenarist/issues/924, https://github.com/dimkanovikov/KITScenarist/issues/923, https://github.com/dimkanovikov/KITScenarist/issues/922, https://github.com/dimkanovikov/KITScenarist/issues/921, and https://github.com/dimkanovikov/KITScenarist/issues/920 

We can add a feature to log in through google account then sync .docx on Google Docs with KITScenarist to collaborate with others. 

Google Doc is awesome to collaborate and somehow sync it with KITScenarist, it will be game-changing.

**Comment by yury-SB** [comment]
Thanks, @NavpreetDevpuri

We will think about it in the next KIT`s generation - Story Achitect https://starc.app/ after it will be ready for everyday writer work.
