### ISSUE TITLE
Idea - add a feature to add reference photos and videos to scene in the script

### ISSUE THREAD

**Issue by NavpreetDevpuri** [dimkanovikov/KITScenarist#926]
it will show a little icon next to the scene in the script to open a new floating window having reference photos and videos 
and 
Somehow link reference images and videos to the research folders.

**Comment by yury-SB** [comment]
Thanks, @NavpreetDevpuri

We will think about it in the next KIT`s generation - Story Achitect https://starc.app/ after it will be ready for everyday writer work.

**Comment by dimkanovikov** [comment]
What does this ability give to the author?

**Comment by NavpreetDevpuri** [comment]
it will be very convenient 
I am working on a script and I am a beginner I felt that it will be so much better if I can just link reference inside script writing it will be easy for me to remember and work on the whole story efficiently and easy for others to look at the story visually while reading the script they can just click "View references" on some particular scene inside the script writing, and it is also very useful when we want collaborative work.

**Comment by dimkanovikov** [comment]
Nice idea!

**Comment by dimkanovikov** [comment]
Will be implemented in the Starc.
