### ISSUE TITLE
Printing text with white color with white background while printing "Characters Speaking Parts" in "Statistics"

### ISSUE THREAD

**Issue by NavpreetDevpuri** [dimkanovikov/KITScenarist#930]
![ShareX_3Os99daYAV](https://user-images.githubusercontent.com/30471072/92994773-c453c300-f51a-11ea-9f99-0ea092f0f77e.png)

It happens only when selecting the printing option. 
it works fine while selecting save options.

**Comment by yury-SB** [comment]
Thanks, @NavpreetDevpuri

We will think about it in the next KIT`s generation - Story Achitect https://starc.app/ after it will be ready for everyday writer work.

**Comment by dimkanovikov** [comment]
duplicate #881
