### ISSUE TITLE
Add a option to save all characters "Characters Speaking Parts" by one click with pdf having same name as character name.

### ISSUE THREAD

**Issue by NavpreetDevpuri** [dimkanovikov/KITScenarist#931]

**Comment by yury-SB** [comment]
Thanks, @NavpreetDevpuri 

We will think about it in the next KIT`s generation - Story Achitect https://starc.app/ after it will be ready for everyday writer work.

**Comment by dimkanovikov** [comment]
Not sure I correctly understand what do you mean... Can you give me an example of what you mean?

**Comment by NavpreetDevpuri** [comment]
From that option, I can save  "Characters Speaking Parts" for all my characters one by one. 
But it will be very convenient if I can save all my characters speaking parts with just one click instead of saving it for each character manually 
![Scenarist_jcxWD92mAQ](https://user-images.githubusercontent.com/30471072/97984722-29ca7e80-1dfd-11eb-870d-0cecb6de9553.png)

**Comment by dimkanovikov** [comment]
Hm... How do you plan to use this option?

**Comment by NavpreetDevpuri** [comment]
> Hm... How do you plan to use this option?

in my case, I wanted to study a particular character a little deeper and trying to improve their dialogues in google docs

 I also able to see when we somehow connect KIT with google docs as mentioned at https://github.com/dimkanovikov/KITScenarist/issues/925 we need to export all characters dialogues files so that we can somehow sync that with google doc 

sometimes creators need to create different dialogue files for each character so they can distribute it to the actual actors or voice artists.

**Comment by dimkanovikov** [comment]
I see, thanks for the explanation. It looks like a very specific case related to your workflow.
