### ISSUE TITLE
Feature Request: export of Statistics as table 

### ISSUE THREAD

**Issue by Lukas2019** [dimkanovikov/KITScenarist#933]
Hi,
I would like to use The Statistics Reports in LibreOffice Calce. Could you add an export to an compatible format? 
As: .ods , .csv  or .xls

Regards

**Comment by yury-SB** [comment]
Hi, @Lukas2019 !

We will think about new export format of statistic in the next KIT`s generation - Story Achitect https://starc.app/ after it will be ready for everyday writer work.
