### ISSUE TITLE
custom text styling / formatting (feature)

### ISSUE THREAD

**Issue by amaau** [dimkanovikov/KITScenarist#937]
I miss the ability to customize the font, color and style: both change a specific piece of text, and be able to customize defaults for certain line types.
I know there are strict formatting rules for screenplays and customization isn't encouraged, 
but sometimes I want to ignore them, especially during first phase of development, and also the line type "non printable text" looks rather bad, weird color,  weird font, would like to at least change that.
Thanks, amazing program!

**Comment by dimkanovikov** [comment]
Hey, you can set up your custom template and use it. Just go to the Settings - Templates Library - press the Plus icon and configure it the way you like.

Also, you can style your text as Bold/Italics/Underline with standard shortcuts or with a context menu for the selected text.

**Comment by amaau** [comment]
Cool, thank you!

**Comment by dimkanovikov** [comment]
Plus, you can configure non printable text color in the settings - script editor - common
