### ISSUE TITLE
Feature request: Plaintext project file

### ISSUE THREAD

**Issue by amaau** [dimkanovikov/KITScenarist#939]
If the project files were plaintext, we could sometimes choose to edit / analyze projects in the geek way, with our favorite text editors, without importexporting every time.
We could do things like: advanced find replace, custom analyzis and breakdown, use git to manage screenplay versions, write and share plugins for screenplay development on something like npm, apm, sublime, etc.
This would be the best feature a screenplay editor can possibly have.

**Comment by dimkanovikov** [comment]
I think, that it's simpler to build a script that will be extract content from the project file than rebuild the application to work with a hierarchy of plaintext files :)

Plus I'm not a fan of this style of content storing. For most users, it's much simpler to send one file, which will contain all of the project documents, than compress the folder and then send an archive.

**Comment by amaau** [comment]
I agree, a single file is definitely better than a hierarchy, but how about XML?
For example, Adobe uses a single (zipped) XML for their project file in most apps.
A non zipped XML could both contain all project data and allow the editing / management possibilities I meant.
Thanks

**Comment by dimkanovikov** [comment]
In fact, we use xml for the content saved in the project file, but difference is that all of them placed not in the archive but in the database file. Check out this https://github.com/dimkanovikov/KITScenarist/wiki/kitsp-File-Fomat for further information about it.

**Comment by amaau** [comment]
Thank you!
