### ISSUE TITLE
Text to Speech

### ISSUE THREAD

**Issue by b4zz4** [dimkanovikov/KITScenarist#942]
The possibility of reproducing all or part of the script with a synthesizer. 
Text to speech to help dyslexic screenwriters. 

Espeak, Mbrolla, etc

**Comment by dimkanovikov** [comment]
Hmm... can you provide a bit more information about how you would like to this option work in the app?

**Comment by b4zz4** [comment]
https://cdn.masto.host/mographsocial/media_attachments/files/105/878/095/670/915/591/original/390e0e4003785363.mp4

By persuading a gedit key link reads the text. This doesn't work well with QT, but I think it's practical for dyslexia and to listen to the dialogue.

**Comment by dimkanovikov** [comment]
Aha, thanks, I got it. Good idea. This will be implemented in version 2, our KIT next-gen app called [Starc](https://starc.app).
