### ISSUE TITLE
Add the "image gallery" in the android version?

### ISSUE THREAD

**Issue by CavaleriOmar** [dimkanovikov/KITScenarist#946]
Would it be possible to have (for me) the very convenient "image gallery" function of the desktop version also on the android version?  Since I paid for it (I'm not complaining, I believe in this project and I want to support it) ... it is true that there are no usable alternatives with KITScenarist, but such a function in my opinion is a serious lack on android ...  it would make it less palatable.

**Comment by dimkanovikov** [comment]
This one is on the radar!

**Comment by dimkanovikov** [comment]
Gallery was added
