### ISSUE TITLE
Would it be possible to write dialogue at the same line as Character?

### ISSUE THREAD

**Issue by Makimars** [dimkanovikov/KITScenarist#948]
Title says it all. Having a newline after every section just feels wasteful and it's not as readable as it could've been. It introduces additional space between character and dialogue which makes them feel separate to the eye.

**Comment by dimkanovikov** [comment]
Hello. There is no option for doing this. It will be possible in our next-gen app [Story Architect](https://starc.app), you can find the repo [here](https://github.com/dimkanovikov/starc).
