### ISSUE TITLE
Add a command to break to new page 

### ISSUE THREAD

**Issue by CavaleriOmar** [dimkanovikov/KITScenarist#949]
I know that KITScenarist is not a simple text editor, but I am using it for a manga script, and for the draftsman's convenience a page of text needs to be a board.
Now, often the script page is shorter, so to respect this I have to "cheat", but it would be nice to have a command to wrap on a new page, so that if I make changes I don't have to worry about removing/putting blank lines below to maintain spacing.

**Comment by dimkanovikov** [comment]
Hello @CavaleriOmar , we don't plan to add this feature to the KIT Scenarist. But we plan to add it in the [Story Architect](https://starc.app), which is a KIT 2.0. Plus we plan to add in the Starc independent module for the Comic scripts. It will be great if you can share with us your needs/ideas as a manga writer to the Starc [repo](https://github.com/dimkanovikov/starc), or via email support@starc.app
