### ISSUE TITLE
Multiple scripts per project 

### ISSUE THREAD

**Issue by clorl** [dimkanovikov/KITScenarist#952]
First of all, I love KIT Scenarist, thanks for making this possible/
A lot of people like to write series and when you do that, you'd like to have everything in the same project. Thing is : you can't export one episode at a time.

It would be useful to have multiple scenarios per project, or being able to export one folder at a time. 

The benefit of having multiple scenarios is that scene count is reset everytime, but it could be an export setting for PDF.

**Comment by dimkanovikov** [comment]
Hello, my friend!

We don't plan to add this feature to the KIT Scenarist, but we already do it for our next-gen app called [Story Architect](https://starc.app).
