### ISSUE TITLE
Spell Check crashes the app

### ISSUE THREAD

**Issue by tahatorabpour** [dimkanovikov/KITScenarist#955]
I really love this application and I'm actively using it to write scripts. I love the workflow and the features. However, this app is a unstable and prone to crashing. One issue that I managed to narrow down was that toggling Spell Check on, crashes the app instantly when trying to open a project.
This application would become a dream application when the crashing bugs are taken care of.

I'm using the  latest AppImage on Linux.

**Comment by dimkanovikov** [comment]
Hello,

Can you check this case
- turn on spelling
- change language
- open project

Does crash gone or still here?

**Comment by tahatorabpour** [comment]
Yeah apparently the crash only happens when selecting `English (US)` as the dictionary language. It works fine on every other language that I tested, including `English (UK)`

**Comment by dimkanovikov** [comment]
A-ha, thanks! looks like something went wrong with downloading dictionary at first time and now woks incorrect. I'll check it!

**Comment by dimkanovikov** [comment]
Didn't reproduced these days
