### ISSUE TITLE
Feature Request: Uppercase / Lowercase for text editing

### ISSUE THREAD

**Issue by Formwarp** [dimkanovikov/KITScenarist#959]
Hi!
It would be _extremely_ helpful to be able to toggle text case, similar to how it works in Word. Scripts I edit often emphasize words with capitalization, and being able to toggle individual word capitalization would massively speed up the editing process. To be clear, I'm  not referring to the capitalization of an entire element type, just singular words in the same way they can be bold, underlined or italicized.
Best

**Comment by dimkanovikov** [comment]
Hello! Try to use the shortcut Ctrl+Up/Down arrow to change words capitalization.

**Comment by Formwarp** [comment]
Thanks! That helps a lot! Are those sorts of shortcuts documented anywhere?

**Comment by dimkanovikov** [comment]
Nope...
