### ISSUE TITLE
Character Arc vs Order of Reveal to the Audience

### ISSUE THREAD

**Issue by david-wendelken** [dimkanovikov/KITScenarist#960]
First of all, thanks for this tool! It's got lots and lots of great features and will get more and more useful as I move forward with it.

Here's a new feature I would like to see (and why).

The scenario cards view is great for laying out the order in which scenes will be presented to the audience.

A character arc is the things that happen to a character as they change during the story. It has a chronological order. I might choose to reveal that character arc in a different order to the audience. However, when I'm trying to write my script it would be handy to be able to see those scenes in character arc order, not audience presentation order.

And, of course, more than one character may have a character arc in a story, and a given scene might be part of more than one character's story arc. So, it's important to be able to organize scenes by multiple character arcs.

I would love a card view that helped me with that. Oh, and since a scene might be in more than one arc, when I choose it in one character arc, it should be highlighted in the other character arcs while the selection is active.

Hope you find this an interesting idea!

**Comment by david-wendelken** [comment]
Ok, I've found out how to add multiple colors to a scenario card so that can be used for multiple character arcs.

But it would still be good to be able to lay out the cards in order of reveal to the audience (which is what you have now) and in character arc order.

**Comment by dimkanovikov** [comment]
Hi! We plan to add the view you talk about with our next-gen app [Story Architect](https://github.com/story-apps/starc). This will be a timeline editor with the ability to group characters' scenes/events in lines.

**Comment by david-wendelken** [comment]
Excellent!
