### ISSUE TITLE
Drag and drop character names and locations from research list into script or cards or scene/act edit screens.

### ISSUE THREAD

**Issue by david-wendelken** [dimkanovikov/KITScenarist#961]
Drag and drop character names and locations from research list into script or cards or scene/act edit screens.

That way, we don't mis-spell the names and the reports by location or character will be correct because the input data driving them is correct.

**Comment by dimkanovikov** [comment]
Can you give me a bit more details about this issue -- did the misspelled locations/characters were a result of imported script or they were entered directly in the app (with the characters/locations names hint popup)?

**Comment by david-wendelken** [comment]
Ok, in using the product more, I've figured out the trick to this.

I was writing the scenario heading or the character line, then marking it as a scenario heading or character line.

Instead, if I mark it as the correct type of line I get hint popups.    That's perfectly workable, so ignore this request. :)

**Comment by dimkanovikov** [comment]
Good to know
