### ISSUE TITLE
Print Preview Script controlled by hidden Export parameters

### ISSUE THREAD

**Issue by david-wendelken** [dimkanovikov/KITScenarist#966]
The Export menu option has three tabs, one for Research, Outline and Script.    

What is not obvious is that the Print Preview Script menu option is controlled by whatever the settings are on the last export that was done.   If you exported an outline, the Print Preview Script option will only print an outline, not the script.

The menu option should either always preview the full script or, much better, give you an option to pick which one to print preview.

**Comment by dimkanovikov** [comment]
Hey! Thanks. Basically, this option is designed to be more like the shortcut for the Print preview button from the export dialog. The use case is very simple - you want to get a printable version of your work, no matter this is a research, outline, or script itself. The first time you configure output via export dialog and then just use "shortcut" to polish it.

I'll update this menu item text so users feel more comfortable with its behavior.

**Comment by dimkanovikov** [comment]
Will be fixed in the next update
