### ISSUE TITLE
[Feature Request] Map Shift + Enter to "break into a new line without skipping a line"

### ISSUE THREAD

**Issue by hyuri** [dimkanovikov/KITScenarist#967]
Hi
The ability to break into a new line without skipping a line is missing.
I propose Shift + Enter be mapped to breaking into a new line without skipping a line. This feature in available for example in the screenwriting software Fade In, as well as other text editors.

I often break into a new line, both as a stylistic choice and to give weight as well as to maintain structural clarity, and many screenwriters I know do the same, so this would be extremely useful.

This is especially important to have because new lines/blocks of text with skipped lines before and after can imply importance. A new line or block that stands by itself — meaning: that it isn't surrounded by other lines — can imply that the information contained in it is of special importance... it has more weight.

Example:
![Shift + Enter New Line](https://user-images.githubusercontent.com/18584014/149653447-96414334-43cc-431f-b06c-1a4e86c847aa.jpg)

**Comment by dimkanovikov** [comment]
This is already implemented in the Story Architect. No plans to backport it to the KIT Scenarist.
