### ISSUE TITLE
[Feature Request] Ability to change keyboard shortcuts

### ISSUE THREAD

**Issue by hyuri** [dimkanovikov/KITScenarist#968]
Hi
It would be nice to be able to change keyboard shortcuts.

Particularly, I'm looking to change "toggle fullscreen mode" from F5 to F11 (GNU/Linux and Windows) and Shift + Command + F (mac OS) to maintain consistency within these systems.

**Comment by dimkanovikov** [comment]
Hello. We don't plan to add such a feature to the KIT Scenarist, since it is in maintenance mode right now. But we plan to allow users to configure shortcuts with our next-gen screenwriting app [Story Architect](https://github.com/story-apps/starc).
