### ISSUE TITLE
Changes made in Fonts through templates is not supported in PDF or in Print Preview.

### ISSUE THREAD

**Issue by AnkVrm** [dimkanovikov/KITScenarist#975]
I created a new template using a base template. Then changed the Dialogues font and it successfully applies to the script editor in the software. But when I try to export as PDF the changes aren't applied to the final PDF. Even the print preview doesn't show the changes.
Is there any possible solution for this issue?

**Comment by dimkanovikov** [comment]
In the export dialog check advanced option and select your template to app use it for export too.
